// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIm3bpv7O6CIm3cpKL6Usle75GM2JBRO8',
    appId: '1:416645521398:android:09cfc5a85dd36c251e31d7',
    messagingSenderId: '416645521398',
    projectId: 'airplane-e018c',
    storageBucket: 'airplane-e018c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPGJfGSK4G5OxM6hvfNK3kUCQyNebW4ag',
    appId: '1:416645521398:ios:c598eb226c5f733e1e31d7',
    messagingSenderId: '416645521398',
    projectId: 'airplane-e018c',
    storageBucket: 'airplane-e018c.appspot.com',
    iosClientId: '416645521398-6h2q6g398f3qcfu2hq2li86jt11q8nqa.apps.googleusercontent.com',
    iosBundleId: 'com.artysis.airplane',
  );
}
